/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.helloweenvsfei.forum.struts.action;

import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.helloweenvsfei.forum.bean.Person;
import com.helloweenvsfei.forum.bean.Reply;
import com.helloweenvsfei.forum.bean.Thread;
import com.helloweenvsfei.forum.service.IPersonService;
import com.helloweenvsfei.forum.service.IReplyService;
import com.helloweenvsfei.forum.service.IThreadService;
import com.helloweenvsfei.forum.struts.form.ReplyForm;
import com.helloweenvsfei.forum.struts.util.PersonInfo;
import com.helloweenvsfei.forum.struts.util.PersonUtil;

/**
 * MyEclipse Struts Creation date: 07-04-2008
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/reply" name="replyForm" input="/form/reply.jsp"
 *                parameter="action" scope="request" validate="true"
 */
public class ReplyAction extends ForumAction {

	private IPersonService<Person> personService;

	private IThreadService<Thread> threadService;

	private IReplyService<Reply> replyService;

	public ActionForward list(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		ReplyForm replyForm = (ReplyForm) form;

		return null;
	}

	public ActionForward initAdd(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		ReplyForm replyForm = (ReplyForm) form;

		Thread thread = threadService.find(Thread.class, replyForm.getThread()
				.getId());

		request.setAttribute("category", thread.getBoard().getCategory());
		request.setAttribute("board", thread.getBoard());
		request.setAttribute("thread", thread);

		replyForm.setTitle("回复帖子 - 标题：" + thread.getTitle());

		return new ActionForward("add", "/form/reply/addReply.jsp", false);
	}

	public ActionForward add(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		ReplyForm replyForm = (ReplyForm) form;

		Thread thread = threadService.find(Thread.class, replyForm.getThread()
				.getId());

		PersonInfo personInfo = PersonUtil.getPersonInfo(request, response);
		Person person = personService.find(Person.class, personInfo.getId());

		Reply reply = replyForm.getReply();
		reply.setThread(thread);
		reply.setDateCreated(new Date());
		reply.setDeleted(false);

		reply.setAuthor(person);

		replyService.create(reply);

		request.setAttribute("category", thread.getBoard().getCategory());
		request.setAttribute("board", thread.getBoard());
		request.setAttribute("thread", thread);
		request.setAttribute("reply", reply);
		
		replyForm.setTitle("回复帖子 - 标题：" + thread.getTitle());

		return new ActionForward("success", "/form/reply/success.jsp", false);
	}

	public IReplyService<Reply> getReplyService() {
		return replyService;
	}

	public void setReplyService(IReplyService<Reply> replyService) {
		this.replyService = replyService;
	}

	public IThreadService<Thread> getThreadService() {
		return threadService;
	}

	public void setThreadService(IThreadService<Thread> threadService) {
		this.threadService = threadService;
	}

	public IPersonService<Person> getPersonService() {
		return personService;
	}

	public void setPersonService(IPersonService<Person> personService) {
		this.personService = personService;
	}
}