/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.helloweenvsfei.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.helloweenvsfei.struts.form.HelloForm;

/**
 * MyEclipse Struts Creation date: 04-29-2008
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/hello" name="helloForm" input="/form/hello.jsp"
 *                scope="request" validate="true"
 * @struts.action-forward name="success" path="helloSuccess.jsp"
 */
public class HelloAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		// 表单对象
		HelloForm helloForm = (HelloForm) form;

		// 如果没有输入 name
		if (helloForm.getName() == null
				|| helloForm.getName().trim().length() == 0) {

			// 则返回输入页面 也就是 /form/hello.jsp 配置在 struts-config.xml 中
			return mapping.getInputForward();
		}
		
		// 转到 success 页面 也就是 /form/helloSuccess.jsp 配置在 struts-config.xml 中
		return mapping.findForward("success");
	}
}