/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.helloweenvsfei.struts.action;

import java.sql.SQLException;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.helloweenvsfei.struts.bean.Person;
import com.helloweenvsfei.struts.dao.PersonDAO;
import com.helloweenvsfei.struts.form.TagForm;

/**
 * MyEclipse Struts Creation date: 05-03-2008
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/tag" name="tagForm" input="/form/tag.jsp"
 *                scope="request" validate="true"
 */
public class TagAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws SQLException
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws SQLException {

		TagForm tagForm = (TagForm) form;

		tagForm.setCheckbox("音乐");
		tagForm.setMultibox(new String[] { "选项一", "选项二" });
		tagForm.setHidden("隐藏的文本域");
		tagForm.setPassword("这里是密码");
		tagForm.setRadio("女");
		tagForm.setSelect("选项二");
		tagForm.setText("这里是文本域");
		tagForm.setTextarea("这里是一段文本\r\n这是第二行");

		PersonDAO personDAO = new PersonDAO();
		List<Person> personList = personDAO.listPersons(getDataSource(request)
				.getConnection());

		request.setAttribute("personList", personList);

		return mapping.getInputForward();
	}
}