/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.helloweenvsfei.struts.action;

import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.helloweenvsfei.struts.form.UploadForm;

/**
 * MyEclipse Struts Creation date: 05-03-2008
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/upload" name="uploadForm" input="/form/upload.jsp"
 *                scope="request" validate="true"
 */
public class UploadAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws Exception
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws Exception {

		UploadForm uploadForm = (UploadForm) form;

		if ("upload".equals(uploadForm.getAction())) {
			return upload(mapping, form, request, response);
		}

		return mapping.getInputForward();
	}

	public ActionForward upload(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws Exception {

		UploadForm uploadForm = (UploadForm) form;

		StringBuffer buffer = new StringBuffer();
		buffer.append("<style>body {font-size: 12px; }</style>");

		if (uploadForm.getFile() != null
				&& uploadForm.getFile().getFileSize() > 0) {

			// 文件夹/WEB-INF/classes
			File classes = new File(getClass().getClassLoader().getResource("")
					.getFile());

			// 文件夹/upload
			File uploadFolder = new File(classes.getParentFile()
					.getParentFile(), "upload");

			uploadFolder.mkdirs();

			// 保存到 /upload 下面
			File file = new File(uploadFolder, uploadForm.getFile()
					.getFileName());

			OutputStream ous = null;
			InputStream ins = null;

			try {
				byte[] b = new byte[1024];
				int len = 0;

				ins = uploadForm.getFile().getInputStream();
				ous = new FileOutputStream(file);

				while ((len = ins.read(b)) != -1)
					ous.write(b, 0, len);
			} finally {
				ins.close();
				ous.close();
			}

			buffer.append("文件：<a href=upload/" + file.getName()
					+ " target=_blank>" + file.getName() + "</a><br/>");
		} else {
			buffer.append("文件：没有选择文件<br/>");
		}

		buffer.append("备注：" + uploadForm.getText() + "<br/>");

		response.setCharacterEncoding("UTF-8");
		response.getWriter().write(buffer.toString());

		return null;
	}
}