/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.helloweenvsfei.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.helloweenvsfei.struts.bean.Person;
import com.helloweenvsfei.struts.form.UseBeanForm;

/**
 * MyEclipse Struts Creation date: 05-06-2008
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/useBean" name="useBeanForm" input="/form/useBean.jsp"
 *                scope="request" validate="true"
 */
public class UseBeanAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws Exception
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws Exception {

		UseBeanForm useBeanForm = (UseBeanForm) form;

		if ("add".equals(useBeanForm.getAction())) {

			Person person = useBeanForm.getPerson();

			response.getWriter().println(
					"person.account: " + person.getAccount());
			response.getWriter().println("person.name: " + person.getName());

			return null;
		}

		return mapping.getInputForward();
	}
}