/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.helloweenvsfei.forum.struts.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionMapping;

import com.helloweenvsfei.forum.bean.Board;
import com.helloweenvsfei.forum.bean.Category;

/**
 * MyEclipse Struts Creation date: 07-04-2008
 * 
 * XDoclet definition:
 * 
 * @struts.form name="boardForm"
 */
public class BoardForm extends ForumForm {

	private Category category = new Category();

	private Board board = new Board();

	private int[] adminId;

	/*
	 * Generated Methods
	 */

	/**
	 * Method validate
	 * 
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/**
	 * Method reset
	 * 
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	public Board getBoard() {
		return board;
	}

	public void setBoard(Board board) {
		this.board = board;
	}

	public Category getCategory() {
		return category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public int[] getAdminId() {
		return adminId;
	}

	public void setAdminId(int[] adminId) {
		this.adminId = adminId;
	}
}