/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.helloweenvsfei.spring.action;

import java.util.Date;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.springframework.util.Assert;

import com.helloweenvsfei.spring.form.Cat2Form;
import com.helloweenvsfei.spring.orm.Cat;
import com.helloweenvsfei.spring.orm.ICatService;

/**
 * MyEclipse Struts Creation date: 06-30-2008
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/cat2" name="cat2Form" input="/form/listCat2.jsp"
 *                scope="request" validate="true"
 */
public class Cat2Action extends Action {

	private ICatService catService;

	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		Cat2Form cat2Form = (Cat2Form) form;

		if ("add".equals(cat2Form.getAction()))
			return this.add(mapping, form, request, response);

		return this.list(mapping, form, request, response);
	}

	public ActionForward add(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		Cat2Form cat2Form = (Cat2Form) form;

		Assert.hasLength(cat2Form.getName(), "名字不能为 null");

		Cat cat = new Cat();
		cat.setName(cat2Form.getName());
		cat.setCreatedDate(new Date());

		catService.createCat(cat);

		return this.list(mapping, form, request, response);
	}

	public ActionForward list(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		List<Cat> catList = catService.listCats();

		request.setAttribute("catList", catList);

		return mapping.findForward("list");
	}

	public ICatService getCatService() {
		return catService;
	}

	public void setCatService(ICatService catService) {
		this.catService = catService;
	}
}